/**
 * GENERATED by `xanots routes --emit`. Do not edit.
 *
 * Plain data plus one interpolator — this file imports nothing, so a frontend
 * gets the typed path/verb (and socket) contract without pulling the SDK runtime
 * into its bundle. Regenerate after changing an endpoint's name, verb, or api
 * group, or a realtime server's or channel's name.
 */

/**
 * An own key only. Every lookup here is keyed by a caller's string, and a plain
 * object answers `toString`, `constructor` or `hasOwnProperty` from its
 * prototype — a name no route, channel or param carries would read as one.
 */
function own<T>(record: Record<string, T>, key: string): T | undefined {
  return Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined;
}

function fillParams(
  label: string,
  noun: string,
  template: string,
  params?: Record<string, string | number>,
  encode = false,
): string {
  const declared = [...template.matchAll(/\{([^/{}]+)\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        `${label}: \`${key}\` is not a {param} of this ${noun}.` +
          (declared.length ? ` Expected: ${declared.join(", ")}.` : ` This ${noun} is static.`),
      );
    }
  }
  return template.replace(/\{([^/{}]+)\}/g, (_all, key: string) => {
    const value = own(params ?? {}, key);
    if (value === undefined || value === null || value === "") {
      throw new Error(`${label}: missing a value for the path param \`${key}\`.`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(`${label}: the path param \`${key}\` is ${value}.`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot contain "/" — ` +
          `it would address a different ${noun}.`,
      );
    }
    if (!encode) return text;
    // A "." or ".." segment is REMOVED before routing (and takes the segment
    // before it), and encoding does not help — the URL standard reads "%2e" as
    // a dot for that check too. Everything else rides percent-encoded.
    if (/^(\.|%2e){1,2}$/i.test(text)) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot be "${text}" — ` +
          `a "." or ".." segment addresses a different ${noun}.`,
      );
    }
    return encodeURIComponent(text);
  });
}

export const ROUTES = {
  "POST auth/demo": { verb: "POST", path: "/api:authn/auth/demo" },
  "GET auth/demo/personas": { verb: "GET", path: "/api:authn/auth/demo/personas" },
  "POST auth/login": { verb: "POST", path: "/api:authn/auth/login" },
  "GET auth/me": { verb: "GET", path: "/api:authn/auth/me" },
  "POST auth/signup": { verb: "POST", path: "/api:authn/auth/signup" },
  "POST agent/retrieve": { verb: "POST", path: "/api:disclosure/agent/retrieve" },
  "GET audit": { verb: "GET", path: "/api:disclosure/audit" },
  "GET records": { verb: "GET", path: "/api:disclosure/records" },
  "POST records/retrieve": { verb: "POST", path: "/api:disclosure/records/retrieve" },
  "GET requests": { verb: "GET", path: "/api:disclosure/requests" },
  "POST requests": { verb: "POST", path: "/api:disclosure/requests" },
  "GET requests/{request_id}": { verb: "GET", path: "/api:disclosure/requests/{request_id}" },
  "POST requests/{request_id}/status": { verb: "POST", path: "/api:disclosure/requests/{request_id}/status" },
  "GET rules": { verb: "GET", path: "/api:disclosure/rules" },
  "POST rules/activate": { verb: "POST", path: "/api:disclosure/rules/activate" },
  "GET rules/active": { verb: "GET", path: "/api:disclosure/rules/active" },
} as const;

/**
 * Every endpoint in this workspace, keyed `"<VERB> <name>"` (e.g. `"GET listings"`),
 * or `"<group>:<VERB> <name>"` when that pair is in more than one api group.
 */
export type RouteName = keyof typeof ROUTES;

export function routePath(name: "POST auth/demo"): string;
export function routePath(name: "GET auth/demo/personas"): string;
export function routePath(name: "POST auth/login"): string;
export function routePath(name: "GET auth/me"): string;
export function routePath(name: "POST auth/signup"): string;
export function routePath(name: "POST agent/retrieve"): string;
export function routePath(name: "GET audit"): string;
export function routePath(name: "GET records"): string;
export function routePath(name: "POST records/retrieve"): string;
export function routePath(name: "GET requests"): string;
export function routePath(name: "POST requests"): string;
export function routePath(name: "GET requests/{request_id}", params: { "request_id": string | number }): string;
export function routePath(name: "POST requests/{request_id}/status", params: { "request_id": string | number }): string;
export function routePath(name: "GET rules"): string;
export function routePath(name: "POST rules/activate"): string;
export function routePath(name: "GET rules/active"): string;

export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  // Read through a widened view: a workspace with no endpoints at all makes
  // `RouteName` `never`, which cannot index the literal type.
  const route = own(ROUTES as Record<string, { verb: string; path: string }>, name);
  if (!route) {
    throw new Error(
      `routePath: unknown route "${String(name)}". Routes are keyed "<VERB> <name>", ` +
        'e.g. "GET listings" — regenerate the manifest if the endpoint is new.',
    );
  }
  return fillParams(`routePath("${String(name)}")`, "route", route.path, params, true);
}
